### PR TITLE
Bedpe overlap

### PR DESCRIPTION
**Pull request by sweavs111**

### CODE REVIEW

**Comment by RavenYL** [comment]
From this page: https://stackoverflow.com/questions/11183788/in-a-git-repository-how-to-properly-rename-a-directory
git mv bedPeOverlap tmp
git mv tmp bedpeOverlap

What Craig mentioned at code review is
mkdir bedpeOverlap
git mv bedPeOverlap/files bedpeOverlap/files
rm -r bedPeOverlap (maybe?)
and then git add, commit, push?

**Comment by rimangan** [comment]
It looks like the bedpeOverlap executable has been pushed in this PR and should be removed

**Comment by RavenYL** [comment]
Should this PR be closed and deleted, since it seems like the renaming is already complete?

**Review by RavenYL — COMMENTED** [review]
Should this PR be closed and deleted, since it seems like the renaming is complete?

**Comment by craiglowe** [comment]
Yes, I think this should be closed.

**Pull request closed without merging**
