### PR TITLE
git author aliases

### PR DESCRIPTION
**Pull request by cshoben**
I discovered that many of us are documented in git under various author names and author emails. This complicates the ability to see the commit history for a specific author. I discovered this when `git log` insisted that my last commit was in 2021. 
I found a fix which is to create an alias file for author and author emails, called a `.mailmap` that is a git specific hidden file similar to `.gitignore`
I've credited and edited the file to resolve my username and useremail issues and am happy to edit it further for others as well. 

Some git notes:
This alias file will be used by default for the `$ git shortlog` command. If you want to use it with `$git log` the option `--use-mailmap` must be added. Ex: `$git log --use-mailmap`

Attached is a "before" and "after" for the authors listed. Notice I was labeled as "Chelsea Shoben", "Chelsea S", and "cshoben" with various emails in the before image. The first column is the total number of commits. 
Screen Shot 2022-09-09 at 11 08 57 AM

Screen Shot 2022-09-09 at 11 09 11 AM

### CODE REVIEW

**Review by RavenYL — COMMENTED** [review]
Thank you for catching this! I tried fixing my names. Could you help me check if I did it right?

**Review by craiglowe — APPROVED** [review]
This is really helpful and I had not known about .mailmap files (I also had not realized that I had a typo in my email address).  I pushed a commit to address my email typo.

**Comment by cshoben** [comment]
Quick way to check if your changes worked:

git shortlog -se

**Review by RavenYL — APPROVED** [review]

**Review by craiglowe — APPROVED** [review]
Great to have this!

**Pull request merged**
