### PR TITLE
dotToNewick Testing

### PR DESCRIPTION
**Pull request by rimangan**
Testing for dotToNewick, which draws Newick trees from DOT format trees.
https://en.wikipedia.org/wiki/Newick_format
https://en.wikipedia.org/wiki/DOT_(graph_description_language)

### CODE REVIEW

**Comment by rimangan** [comment]
#434

**Comment by rimangan** [comment]
This program outputs a newick tree that looks correct from what I can tell, but I notice that drawNewickTree is unable to parse it, like Christi noted in the issue she raised. However, drawNewickTree is also untested, so I don't know if it's the parser there or an issue here.

**Comment by cfauci** [comment]
Parser on draw newick is good I've used it successfully a whole bunch and last I left it everything was working great. I was also desperately confused because the newicks out of dotToNewick looked right to me too.

**Comment by rimangan** [comment]
> Parser on draw newick is good I've used it successfully a whole bunch and last I left it everything was working great. I was also desperately confused because the newicks out of dotToNewick looked right to me too.

Hmm good to know maybe we can take a look at this together next week.

**Review by cshoben — APPROVED** [review]

**Review by cfauci — APPROVED** [review]

**Review by dasnellings — APPROVED** [review]

**Pull request merged**
